---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-cis-f5-bigip-ctlr
  namespace: default
  labels:
    app.kubernetes.io/instance: bigip-cis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-20.3.0
    release: bigip-cis
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-cis-f5-bigip-ctlr
subjects:
- kind: ServiceAccount
  name: bigip-ctlr
  namespace: default
