---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-cis-f5-bigip-ctlr
  labels:
    app.kubernetes.io/instance: bigip-cis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-20.3.0
    release: bigip-cis
    heritage: Helm 
rules:
  - apiGroups:
      - ''
      - extensions
    resources:
      - nodes
      - services
      - endpoints
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
      - extensions
    resources:
      - events
      - services/status
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - cis.f5.com
    resources:
      - transportservers
      - transportservers/status
      - deployconfigs
      - deployconfigs/status
      - policies
      - ingresslinks
      - ingresslinks/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ''
      - extensions
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
