---
# Source: f5-bigip-ctlr/templates/f5-bigip-ctlr-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigip-ctlr
  namespace: default
  labels:
    app.kubernetes.io/instance: bigip-cis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: f5-bigip-ctlr
    app: f5-bigip-ctlr
    chart: f5-bigip-ctlr-20.3.0
    release: bigip-cis
    heritage: Helm
