apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr-deployment
  template:
    metadata:
      labels:
        app: k8s-bigip-ctlr-deployment
    spec:
      serviceAccountName: bigip-ctlr
      containers:
      - name: cntr-ingress-svcs
        image: registry.connect.redhat.com/f5networks/cntr-ingress-svcs:latest
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: BIGIP_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: bigip-login
        - name: BIGIP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: bigip-login
        command:
        - /app/bin/k8s-bigip-ctlr
        args:
        - --bigip-username=$(BIGIP_USERNAME)
        - --bigip-password=$(BIGIP_PASSWORD)
        - --bigip-url=192.168.110.167
        - --bigip-partition=p2
        - --as3-validation=true
        - --disable-teems=true
        - --log-as3-response=true
        - --static-routing-mode=true
        - --orchestration-cni=ovn-k8s
        - --custom-resource-mode=true
        - --pool-member-type=cluster
        - --insecure=true
        - --namespace=default
        - --log-level=debug