#affinity
affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: Exists
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - infra-node-1
              - infra-node-2
              - infra-node-3

#privileged scc binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: nginx-ingress-sa
  namespace: your-namespace


#security-context
spec:
  template:
    spec:
      serviceAccountName: nginx-ingress-sa
      securityContext:
        runAsUser: 1000950000
      containers:
      - name: nginx-ingress
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE