apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: test-nginx-vs
  namespace: default
spec:
  virtualServerAddress: "10.x.x.x"  # Replace with your desired VIP
  host: test-nginx.example.com      # Replace with your domain
  pools:
  - path: /
    service: test-nginx-svc
    servicePort: 80
    monitor:
      type: http
      interval: 10
      timeout: 31
      send: "GET / HTTP/1.1\r\nHost: test-nginx.example.com\r\n"